Mols/Controllers/ShoppingCartController.cs
using Mols.Models;
using Mols.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mols.Controllers
{
    public class ShoppingCartController : Controller
    {
        List<Item> Items = SampleData.ItemDummy();
        List<Cart> CartsDummy = SampleData.Carts01();

        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the item from dummy data
            var addedItem = Items.Single(i => i.ItemId == id);
            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedItem);
            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
       
        //
        // AJAX: /ShoppingCart/RemoveFromCart/
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Get the name of the item to display confirmation
            string itemName = CartsDummy.Single(item => item.RecordId == id).Item.Name;
            // Remove from cart
            int itemCount = CartsDummy.Where(c => c.RecordId == id).Select(t => t.QtyOrder).FirstOrDefault();
            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(itemName) + " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

Mols/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mols.Models;

namespace Mols.Controllers
{
    public class StoreController : Controller
    {
        List<Category> Categories = SampleData.CategoryDummy();
        List<Item> Items = SampleData.ItemDummy();
        
        //
        // GET: /Store/
        public ActionResult Index()
        {          
            return View(Categories);
        }

        //
        // GET: /Store/Browse
        public ActionResult Browse(string categoryName)
        {
            // Retrieve Category and its Associated Items from database
            var category = Categories.Where(i => i.CategoryName == categoryName).FirstOrDefault();
            category.Items = Items.Where(i => i.CategoryId == category.CategoryId).ToList();

            return View(category);
        }

        //
        // GET: /Store/Details
        public ActionResult Details(int id)
        {
            // Retrieve Category and its Associated Items from database
            var item = Items.Where(i => i.ItemId == id).FirstOrDefault();

            return View(item);
        }

        //
        // GET: /Store/CategoriesMenu
        [ChildActionOnly]
        public ActionResult CategoriesMenu()
        {
            return PartialView(Categories.ToList());
        }
    }
}

Mols/Views/Store/Browse.cshtml
@model Mols.Models.Category

@{
    ViewBag.Title = "Browse Item";
}

<h2>Browsing Category: @Model.CategoryName</h2>
<div class="genre">
    <h3><em>@Model.CategoryName</em> Item</h3>
    <ul id="album-list">
        @foreach (var item in Model.Items)
        {
            <li>
                <a href="@Url.Action("Details", new { id = item.ItemId })">
                    <img alt="@item.Name" src="@item.ItemPictureUrl" />
                    <span>@item.Name</span>
                </a>
            </li>
        }
    </ul>
</div>

Mols/Views/Store/CategoriesMenu.cshtml
@model IEnumerable<Mols.Models.Category>

<ul id="categories">
    @foreach (var category in Model)
    {
        <li>
            @Html.ActionLink(category.CategoryName, "Browse", "Store", new { CategoryName = category.CategoryName }, null)
        </li>
    }
</ul>

Mols/Views/Store/Details.cshtml
@model Mols.Models.Item

@{
    ViewBag.Title = "Item - " + Model.Name;
} <
h2>@Model.Name</h2>
<p>
    <img alt="@Model.Name" src="@Model.ItemPictureUrl" />
</p>
<div id="album-details">
    <p>
        <em>Color:</em>
        @Model.Color
    </p>
    <p>
        <em>Price:</em>
        @String.Format("{0:F}", Model.Price)
    </p>
    <p class="button">
        @Html.ActionLink("Add to cart", "AddToCart",
"ShoppingCart", new { id = Model.ItemId }, "")
    </p>
</div>

Mols/Views/Store/Index.cshtml
@model IEnumerable<Mols.Models.Category>

@{
    ViewBag.Title = "Store";
}

<h2>Index</h2>

<p>
    Select from @Model.Count() categories:
</p>
<ul>
    @foreach (var category in Model)
    {
        <li>@Html.ActionLink(category.CategoryName, "Browse", new { categoryName = category.CategoryName })</li>
    }
</ul>